CREATE TABLE `complaint` (
  `complaintID` int NOT NULL,
  `title` char(50) DEFAULT NULL,
  `act` char(50) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `city` char(50) DEFAULT NULL,
  `dateAdded` date DEFAULT NULL,
  `details` char(50) DEFAULT NULL,
  `complaintSolved` tinyint DEFAULT NULL,
  `complaintTrack` int DEFAULT NULL,
  `victimID` int DEFAULT NULL,
  `policeStationID` int DEFAULT NULL,
  PRIMARY KEY (`complaintID`),
  KEY `fk_complaint` (`victimID`),
  KEY `fk_complaint1` (`policeStationID`),
  CONSTRAINT `fk_complaint` FOREIGN KEY (`victimID`) REFERENCES `person` (`personID`),
  CONSTRAINT `fk_complaint1` FOREIGN KEY (`policeStationID`) REFERENCES `police_station` (`policeStationID`)
);

ALTER TABLE COMPLAINT RENAME COLUMN p_stationID TO policeStationID;
INSERT INTO `complaint`
VALUES (1,'Theft at home','Theft','John Doe','New York','2022-01-01','Theft at John Doe\'s home on Main St',1,100,1,1),
(2,'Assault on Park Ave','Assault','Jane Smith','Los Angeles','2022-02-01','Assault on Park Ave',0,1,2,2),
(3,'Carjacking on Elm St','Carjacking','Mark Johnson','Chicago','2022-03-01','Carjacking on Elm St',0,44,3,3),
(4,'Vandalism on Oak St','Vandalism','Emily Davis','Houston','2022-04-01','Vandalism on Oak St',0,4,4,4),
(5,'Harassment on Pine St','Harassment','Jacob Wilson','Phoenix','2022-05-01','Harassment on Pine St',0,1,5,5),
(6,'Burglary at home','Burglary','Michael Brown','New York','2022-01-01','Burglary at Michael Brown\'s home on Main St',0,6,6,1),
(7,'Fraud at Business','Fraud','Emily Taylor','Los Angeles','2022-02-01','Fraud at Emily Taylor\'s business on Park Ave',0,7,7,2),
(8,'Drug Possession','Drug Possession','David Johnson','Chicago','2022-03-01','Drug possession on Elm St',0,8,8,3),
(9,'Harassment at Work','Harassment','Jessica Davis','Houston','2022-04-01','Harassment at Jessica Davis\'s work on Oak St',0,9,1,4),
(10,'Road Accident','Road Accident','Matthew Wilson','Phoenix','2022-05-01','Road Accident on Pine St',0,1,3,5),
(11,'Cybercrime','Cybercrime','Andrew Garcia','New York','2022-01-01','Cybercrime at Andrew Garcia\'s home on Main St',0,2,2,1),
(12,'Theft at Mall','Theft','Emily Martinez','Los Angeles','2022-02-01','Theft at Emily Martinez\'s mall on Park Ave',0,3,3,2),
(13,'Assault on Public Transit','Assault','Jacob Robinson','Chicago','2022-03-01','Assault on Public Transit on Elm St',0,4,5,3),
(14,'Vandalism at School','Vandalism','Michael Lewis','Houston','2022-04-01','Vandalism at Michael Lewis\'s school on Oak St',0,1,7,4),
(15,'Harassment on Social Media','Harassment','Emily Lee','Phoenix','2022-05-01','Harassment on social media',0,7,8,5),
(16,'Robbery at Night','Robbery','Jacob Hall','New York','2022-01-01','Robbery at night on Main St',0,9,1,1),
(17,'Drug trafficking','Drug trafficking','Michael Allen','Los Angeles','2022-02-01','Drug trafficking on Park Ave',0,8,3,2),
(18,'Murder','Murder','Emily Young','Chicago','2022-03-01','Murder on Elm St',0,5,1,3),
(19,'Armed robbery','Armed robbery','Jacob Hernandez','Houston','2022-04-01','Armed robbery on Oak St',0,6,2,4);
